name: Render paper.pdf
on:
  push:
    branches: [ "main" ] # mainブランチにPushされた時のみ動かすのがおすすめ

# GITHUB_TOKENに書き込み権限を付与
permissions:
  contents: write

jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
        - uses: fontist/setup-fontist@v2
        - run: fontist install --formula "noto_sans_cjk"
        - uses: actions/checkout@v7
        - uses: typst-community/setup-typst@v5
        
        - run: typst compile test.typ test.pdf --font-path ~/.fontist/fonts
        
        # 生成されたPDFをReleaseにアップロード
        - name: Upload to Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: latest
            name: "最新版 PDF (Latest)"
            files: test.pdf
            # Pushのたびに同じタグ(latest)を上書き更新する設定
            make_latest: true